package com.patronage.intive.steps;

import com.patronage.intive.pages.MainPage;
import com.patronage.intive.pages.RadioButtonSubPage;
import io.cucumber.java.en.And;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import org.junit.Assert;

public class ExampleStepdefs {

    /* Beginner TIP: Here you see an example, how to create new objects.
    * This is necessary, when the object is created, you have access to functions and selectors from it. */

    MainPage mainPage = new MainPage();
    RadioButtonSubPage radioButtonSubPage = new RadioButtonSubPage();


    /* Beginner TIP: This strings (eg. "DemoQA site is open") are exactly the same as, ones defined
    in .feature file in resources/features.
    Start with defining steps on feature file, as you later see some part of this code could be autogenerated.
    *   */

    @Given("DemoQA site is open")
    public void demoqaSiteIsOpen() {
        mainPage.openDemoQA();
        mainPage.waitUntilPageOpen();
    }

    @When("user select Element category")
    public void userSelectsElements() {
        mainPage.selectElementsSection();
    }

    @And("select Radio Button tab")
    public void selectRadioButtonTab() {
        mainPage.selectRadioButtonMenuItem();
    }

    @And("select radio button yes")
    public void selectRadioButtonYes() {
        radioButtonSubPage.selectRadioButtonYes();
    }

    @Then("{string} message should be visible")
    public void messageShouldBeVisible(String textMessage) {
        Assert.assertEquals(radioButtonSubPage.getRadioButtonConfirmationMessage(), textMessage);
    }
}
